### ISSUE TITLE
Specifying headers for OPTIONS method (CORS)

### ISSUE THREAD

**Issue by ericpeters0n** [fotinakis/swagger-blocks#85]
Any hints on how to translate  something like this to Swagger-Blocks?
```
      200:
        description: Returns the CORS response headers
        headers:
          Access-Control-Allow-Origin:
            type: string
          Access-Control-Allow-Credentials:
            type: boolean
          Access-Control-Allow-Headers:
            type: array
            collectionFormat: csv
          Access-Control-Allow-Methods:
            type: array
            collectionFormat: csv
          Access-Control-Max-Age:
            type: integer
```
